config/routes.rb
Penguinpostman::Application.routes.draw do

root :to => 'mailings#new'

resources :mailings do
  member do
    post :place_order
  end  
end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :file_path
  mount_uploader :file_path, FileUploader
end

app/models/mailing.rb
class Mailing < ActiveRecord::Base
  mount_uploader :file_path, FileUploader

  attr_accessible :pages, :file_path, :user_email, :user_firstname, :user_lastname, :user_street_1, 
  :user_street_2, :user_city, :user_state, :user_zip, :recipient_firstname, :recipient_lastname, :recipient_street_1, 
  :recipient_street_2, :recipient_city, :recipient_state, :recipient_zip, :order_processed


  before_save :default_values
  def default_values
    self.order_processed = 'false' if self.order_processed.nil?
  end

  # def index(user)
  #   logger.debug(user.inspect)
  # end

  # validates :user_email, presence: true

  def user_fullname
    "#{user_firstname} #{user_lastname}"
  end
  

end

app/models/mailings.rb
class Mailing < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mailings_controller.rb
require 'stripe'

class MailingsController < ApplicationController
	def new
  	@mailing = Mailing.new
  end

  # if our create action renders or redirects, do that
  # otherwise, default to "create" view (the view is the name of action)
  # finally, throw an error, we give up
  def create
  	@mailing = Mailing.new(params[:mailing])

    if @mailing.save
      redirect_to mailing_url(@mailing)
    else
      render action: 'new'
      flash[:notice] = "There were some errors"
    end
  end

  def show
    @mailing = Mailing.find(params[:id])
  end

  def update
  	@mailing = Mailing.find(params[:id])

    if @mailing.update_attributes(params[:mailing])
      redirect_to @mailing, notice: 'Mailing was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
  	
  end

  def place_order
    @mailing = Mailing.find(params[:id])
    unless @mailing.order_processed
      begin
        @charge = Stripe::Charge.create(
          :amount => 400,
          :currency => "usd",
          :card => params[:stripeToken], # obtained with Stripe.js
          :description => "Charge for test@example.com"
        )
        flash[:notice] = "Thank you for your order! You should expect it to arrive within 4-6 business days!"
        @mailing.order_processed = true
        @mailing.save
        #Tell the UserMailer to send a confirmation email after save
        UserMailer.order_confirmation_email(@mailing).deliver
        #Tell admins that a new order has been placed
        UserMailer.order_submit(@mailing).deliver
        redirect_to root_path

      rescue Stripe::CardError => e
        # flash[:error] = e.message
        # redirect_to edit_mailing_path(@mailing.id)
        redirect_to edit_mailing_path(@mailing.id), :notice => "#{e.message}"
      end
    end   
  end

  def edit
  	@mailing = Mailing.find(params[:id])
  end

  def index
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mailings_helper.rb
module MailingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="recursive.com.au">

	
  <title>Penguin Postman</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "animate-custom", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-responsive", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-responsive.min", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag    "general", :media => "all" %>
  <%= stylesheet_link_tag    "paper", :media => "all" %>
  <%= stylesheet_link_tag    "styles", :media => "all" %>

  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

  <%= javascript_include_tag "bootstrap" %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= javascript_include_tag "script" %>
  <%= javascript_include_tag "checkout" %>

  <%= csrf_meta_tags %>

  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600" rel="stylesheet">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300" rel="stylesheet" type="text/css">
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  
</head>
<body>

<% if notice %>
  <p class="notice info message "><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert info message"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/mailings/edit.html.erb


<h1>This is the EDIT page!!!!!! WOOOOOO!</h1>

<%= form_for @mailing do |f| %>
  
  <%= f.label "First Name" %>:
  <%= f.text_field :user_firstname %><br />
  <%= f.label "Last Name" %>:
  <%= f.text_field :user_lastname %><br />
  
  <%= f.label "Street Address 1" %>:
  <%= f.text_field :user_street_1 %><br />

  <%= f.label "Street Address 2" %>:
  <%= f.text_field :user_street_2 %><br />

  <%= f.label "City" %>:
  <%= f.text_field :user_city %><br />

  <%= f.label "State" %>:
  <%= f.text_field :user_state %><br />

  <%= f.label "Zip" %>:
  <%= f.text_field :user_zip %><br />

<br />
<br />

  <%= f.label "First Name" %>:
  <%= f.text_field :recipient_firstname %><br />
  <%= f.label "Last Name" %>:
  <%= f.text_field :recipient_lastname %><br />
  
  <%= f.label "Street Address 1" %>:
  <%= f.text_field :recipient_street_1 %><br />

  <%= f.label "Street Address 2" %>:
  <%= f.text_field :recipient_street_2 %><br />

  <%= f.label "City" %>:
  <%= f.text_field :recipient_city %><br />

  <%= f.label "State" %>:
  <%= f.text_field :recipient_state %><br />

  <%= f.label "Zip" %>:
  <%= f.text_field :recipient_zip %><br />  


  <%= f.label :pages %>:
  <%= f.text_field :pages %><br />

  <%= f.label :user_email %>:
  <%= f.text_field :user_email %><br />

  <%= f.submit "Save and Review"%>

<% end %>


<!-- STRIPE -->


<% if false %>
<%= button_to "Submit Order", mailing_path(@mailing.id), :method => "get" %>
<% end %>

app/views/mailings/new.html.erb
<body>
  <%= form_for @mailing do |f| %>
    <div class="container">
        <div id="#header-text" class="row">
            <div class="feature span12">
                <h2 id="first" class="motto hidden-on-load">Send real mail again.</h2>
                <h3 id="second" class="subheader hidden-on-load">In 30 seconds.</h3>
            </div>
        </div>
    </div>
    <div class="container">    
        <div class="row upload">
            <div id="third" class="span12 center hidden-on-load animated fadeInDown">
                <img id="postcard-image" src="/images/penguinpostman.png">
                <%= f.file_field :file_path, :id => 'upload_hidden' %>
                <a id="upload"href="#" class="signup"> <span id="type-of-file">Send an Attachment</span></a>
                <div id="helper-text" style="color: #aaa; font-size: 8px;">(Click to Upload)</div>
            </div>
        </div>
        <div id="letter-form">
            <div class="span12 contact_form">
                <!-- Lets create a CSS3 stamp -->
                <div class="hfeed" style="margin-top: 60px;">
                            <article class="entry post">
                                <header class="entry-header">
                                    <div class="stamp">
                                        <!-- the image -->
                                        <img id="pengin_flyout" style="width: 150px; float: right; margin-top: 20px; margin-right: 20px;" src="../images/penguin_flyout.png">
                                    </div>
                                </header>
                                <div class="entry-content">
                                    <div class="row">
                                        <div class="span12">

                                            <%= form_for @mailing, url: {action: "create"}, html: {class: "contact_form_from"} do |f| %>

                                                <%= f.text_field :user_firstname, :placeholder => "Maker", :style => 'width: 70px; margin-left: 50px;' %>
                                                <%= f.text_field :user_lastname, :placeholder => "Square", :style => 'width: 70px;' %><br>
                                                <%= f.text_field :user_street_1, :placeholder => "716 Congress", :style => 'width: 130px; margin-left: 50px;'%>
                                                <%= f.text_field :user_street_2, :placeholder => "#100", :style => 'width: 40px;'%><br>
                                                <%= f.text_field :user_city, :placeholder => "Austin", :style => 'width: 80px; margin-left: 50px;'%>
                                                <%= f.text_field :user_state, :placeholder => "TX", :style => 'width: 20px;'%>
                                                <%= f.text_field :user_zip, :placeholder => "78701", :style => 'width: 40px;'%><br>
                                                <%= f.text_field :user_email, :placeholder => "youremail@gmail.com", :style => 'width: 170px; margin-left: 50px;'%><br><br><br>
                                                <%= f.text_field :recipient_firstname, :placeholder => "Mr.", :style => 'width: 70px; margin-left: 400px;'%>
                                                <%= f.text_field :recipient_lastname, :placeholder => "President", :style => 'width: 70px;'%><br>
                                                <%= f.text_field :recipient_street_1, :placeholder => "1600 Penn Ave", :style => 'width: 130px; margin-left: 400px;'  %>
                                                <%= f.text_field :recipient_street_2, :placeholder => "#200", :style => 'width: 40px;'  %><br>
                                                <%= f.text_field :recipient_city, :placeholder => "Washington", :style => 'width: 80px; margin-left: 400px; margin-bottom: 30px;'  %>
                                                <%= f.text_field :recipient_state, :placeholder => "DC", :style => 'width: 20px; margin-bottom: 30px;'  %>
                                                <%= f.text_field :recipient_zip, :placeholder => "20500", :style => 'width: 40px; margin-bottom: 30px;' %>
                                            <% end %>
                                        </div>
                                    </div>
                            </article>
                        </div>
                <div class="row center">
                    <a id="submit"href="/mailings" class="signup" style="width: 200px; margin-top: 30px;"> <span>Review Order</span>
                    </a>
                    <br><%= f.submit "Review order", :id => 'submit_hidden' %>
                    <div id="helper-text" style="color: #aaa; font-size: 8px;">(Click to Continue)</div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/views/mailings/show.html.erb
<body>
	<h2 id="first" class="motto">Please review your order.</h2>
	<div class="container">    
		<div id="">
		    <div id="second" class="span12 contact_form">
		        <!-- Lets create a CSS3 stamp -->
		        <div class="hfeed" style="margin-top: 30px;">
		                    <article class="entry post">
		                        <header class="entry-header">
		                            <div class="stamp">
		                                <!-- the image -->
		                                <img id="pengin_flyout" style="width: 150px; float: right; margin-top: 20px; margin-right: 20px;" src="../images/penguin_flyout.png">
		                            </div>
		                        </header>
		                        <div class="entry-content">
		                        	<%= button_to "Edit", edit_mailing_url(@mailing), :method => "get", :style => "color: red; border-bottom: none; text-align: left;"%>
		                            <div class="row">
		                                <div class="span4">
		                                    <div style="margin-top: 15px;">
		                                    	<p style="font-weight: bold;">From:</p>
		                                    	<p><%= @mailing.user_fullname %></p>
		                                    	<p><%= @mailing.user_street_1 %></p>
		                                    	<% if @mailing.user_street_2 %>
		                                    		<p><%= @mailing.user_street_2 %></p>
		                                    	<% end %>
		                                    	<p><%= "#{@mailing.user_city}, #{@mailing.user_state} #{@mailing.user_zip}" %></p>
		                                    	<p><%= @mailing.user_email %></p>
		                                    </div>
		                                </div>
		                                <div id="to_section" class="span4">
		                                    <div style="margin-top: 150px;">
		                                    	<p style="font-weight: bold; font-size: 20px;">To:</p>
		                                    	<p style="font-size: 20px;"><%= "#{@mailing.recipient_firstname} #{@mailing.recipient_lastname}" %></p>
		                                    	<p style="font-size: 20px;"><%= @mailing.recipient_street_1 %></p>
		                                    	<% if @mailing.recipient_street_2 %>
		                                    		<p style="font-size: 20px;"><%= @mailing.recipient_street_2 %></p>
		                                    	<% end %>
		                                    	<p style="font-size: 20px;"><%= "#{@mailing.recipient_city}, #{@mailing.recipient_state} #{@mailing.recipient_zip}" %></p>
		                                    </div>
		                                </div>
		                            </div>
		                    </article>
		                </div>
		    </div>
		</div>
		<div id="third" class="center">Attachment:
			<p><%= @mailing.file_path.path.split('/').last %></p>
		</div>
		<div id="last" class="center" style="display: ;">
			<form action="<%= place_order_mailing_path(@mailing) %>" method="post">
			  <script 
			  	src="https://checkout.stripe.com/v2/checkout.js" 
			  	class="stripe-button"
			    data-key="pk_test_hUrf8D6B8e8qtDHEBm9VVOuP"
			    data-amount="499"
			    data-name="Penguin Postman"
			    data-description="1 page mailing"
			    data-image="/../../images/penguin128.png"></script>
			</form>
		</div>
	</div>
</body>



